# Generated by Django 3.2.11 on 2022-05-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20220512_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
