# Generated by Django 3.2.11 on 2022-05-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_auto_20220515_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
