# Generated by Django 3.2.11 on 2022-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.CharField(choices=[('published', 'Pusblished'), ('dennis', 'Dennis'), (1, 2)], max_length=200, null=True),
        ),
    ]
