# Generated by Django 3.2.11 on 2022-05-21 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0017_auto_20220521_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='Dart', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.CharField(blank=True, choices=[('published', 'Pusblished'), ('pending', 'Pending')], max_length=200, null=True),
        ),
    ]
