# Generated by Django 3.2.11 on 2022-05-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0019_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
